### ISSUE TITLE
Numbers.md - Terminology Suggestion 

### ISSUE THREAD

**Issue by karuthan** [Ezhil-Language-Foundation/RubyKin#11]
**Current:**

ரூபி தர்க ரீதியான பெரியது  `>` and கம்மியானது `<` செயலுறுப்புகளையும் பிரியும்; செயலுருபு என்ற ஒரு கணிதம் அல்ல கணினி செயல் என்று பொருள் -  கூட்டல், கழித்தல் எல்லாம் ஒரு செயலுருபு என்றும் சொல்லலாம்.

-------
**Proposed :**

ரூபி கணித, ஏரண செயல்பாடுகளை செய்யும் ஆற்றல்பெற்றது.  
எ.கா.   

1. **`+`**  கூட்டல் 
2. **`-`**   கழித்தல் 
3. **`>`**  பெரியதா 
4.  **`<`**  சிறியதா

> செயல்பாடு = operation 
> செயற்குறி   = operator 
> ஏரணம் / தருக்கம்    = logic

**Comment by karuthan** [comment]
செயலுருபு  = parameter

**Comment by arcturusannamalai** [comment]
நல்ல பரிந்துரை. இதனை ஒத்து நம்ம இந்த கணினி கோட்பாடுகளை மாற்றி எழுதலாம்.

**Comment by arcturusannamalai** [comment]
Integrated your PR @karuthan - Thanks for this work.
