### ISSUE TITLE
மாறிலி is not variable

### ISSUE THREAD

**Issue by karuthan** [Ezhil-Language-Foundation/RubyKin#2]
- variable = மாறி 
- constant  = மாறிலி  <~ மாறு + இலி <~ மாறு + இல் + இ 

https://github.com/Ezhil-Language-Foundation/RubyKin/blob/master/variables/variable.md#மாறிலி

**Comment by arcturusannamalai** [comment]
நன்றி. இதை சரிசெய்வோம்.

**Comment by jophinep** [comment]
மாறிலி-க்கு பதிலாக மாறினி எனலாம்.

மாறினி = மாறக்கூடியது
கணினி = கணிக்கக்கூடியது

**Comment by karuthan** [comment]
இ - என்பது  அஃறிணை பின்னொட்டு.

கணிக்கும்  + "இ" = கணினி  = computing device
மாறும்   + "இ"  = மாறி  = variable
மாற்றம் + இல்லா + "இ" = மாறிலி  = constant

**Comment by karuthan** [comment]
immutable  = மாற்றுறா 
immutable type  = மாற்றுறா வகை 
immutability  = மாற்றுறாமை
 
readonly = மாற்றறு = மாற்றத்தை அறு

**Comment by arcturusannamalai** [comment]
நல்ல விளக்கம் கொடுத்தீர்கள் கருத்தன். நீங்கள் இதை ஒரு வலை பதிவாக வெளியிடவேண்டும் என்பது ஒரு அன்பு கோரிக்கை.

**Comment by arcturusannamalai** [comment]
Changes made earlier. Close ticket.
