### ISSUE TITLE
Need translation reference file in repo

### ISSUE THREAD

**Issue by jophinep** [Ezhil-Language-Foundation/RubyKin#4]
Now since we have more than one translators for this book, we need to maintain the same translation words (கலைச்சொல் அகராதி). By having this as reference in some file in repo, we can maintain uniformity of terminology when it is translated in Tamil.

For now, I actually read the translated pages to find, if we already have translated some terminology in Tamil (than I write or find them myself). So that, uniformity is maintained across the book.

For example, something like:
```
blocks = தொகுதிகள்
concatenation = ஒட்டு
string = சரம்
```

**Comment by arcturusannamalai** [comment]
வணக்கம் Jophine! மொழிபெயர்ப்புக்கு வருக.
என்னை பொருத்தமட்டில் உங்கள் நடையில் எழுதுங்கள், நாள் editorial corrections (ஆசிரியர் திருத்தம்) கடைசியாக செய்யலாம் என்றும் நினைக்கிரேன்.

பல கலைச்சொற்கள் உண்டு. நாமளும் ஒரு Appendix போட்டு தமிழ் ஆங்கிலம் சமன்ம்பாடை எழுதலாம்.

நன்றி.

**Comment by karuthan** [comment]
இவை அடியவன் தொகுப்பு,
http://karuthan.github.io/vocabulary/new/

@jophinep

**Comment by ilanthendral** [comment]
https://github.com/Ezhil-Language-Foundation/RubyKin/wiki/Terminology-Reference

**Comment by arcturusannamalai** [comment]
நல்ல முன்னேற்றம்  - இளந்தென்றல்  மற்றும் கருத்தன்; நான் திருத்தங்களை எல்லா அத்யாயங்களையும் மொழி பெயர்த்தபின் ஒரே நடையில் வாசிக்க முடிகிறதா என்ற கோணத்தில் ஆசிரியர் திருத்தங்களை கொண்டுவர திட்டடம் செய்கிறேன்.

நன்றி

**Comment by arcturusannamalai** [comment]
Closing - we can use @ilanthendral work on the terminology reference.
